CREATE TABLE [dbo].[Roles]
(
	[Id]		 INT			NOT NULL,
	[CreatedAt]  DATETIME2(7)   NOT NULL DEFAULT GETDATE(),
	[Name]		 NVARCHAR(255)  NOT NULL,
	CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED ([Id] ASC)
)

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Roles_Name]
    ON [dbo].[Roles]([Name] ASC)